version: '3'

services:
  web:
    image: node:alpine
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    command: sh -c "npm install -g http-server && http-server -o -c-1"
    volumes:
      - .:/usr/src/app
